#
#           -|-
#  |   ||   /|   UEFI Variable Tool (UVT) * Release Workflow
#  |   ||  / |   https://github.com/GeographicCone/UefiVarTool
#  `---'`-'  `-  Copyright © 2022 Datasone, © 2023 Piotr Szczepański
#
# Triggers a build and uploads artifacts as release assets

name: "UVT Release"
run-name: "UEFI Variable Tool (UVT) Release"

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  call-build:
    name: "Call Build"
    secrets: inherit
    uses: ./.github/workflows/build.yml
    with:
      version_number: ${{ github.event.release.tag_name }}
      version_word: ${{ github.event.release.prerelease && 'Preview' || 'Release' }}

  release:
    name: "Release UVT"
    needs: call-build
    runs-on: ubuntu-latest

    steps:
    - id: download
      name: "Download Artifacts"
      uses: actions/download-artifact@v4
      with:
        name: ${{ github.event.repository.name }}

    - name: "List Artifacts"
      run: ls -1R ${{ steps.download.outputs.download-path }}

    - name: "Create Release body"
      run: |
        printf "**v%s**\n\n" ${GITHUB_REF/refs\/tags\//} > body.txt
        printf "* %s\n" "Remove header with application version, firmware vendor, firmware version, UEFI revision number. Replace \"Already\" with \"Writing skipped\"" >> body.txt

    - name: "Upload to Release"
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        body_path: ./body.txt
        files: ./uvt.efi
